### ISSUE TITLE
Android resource files not being generated for kmm module

### ISSUE THREAD

**Issue by mikelburkhart** [jcraane/kmm-resources#4]
I have followed the instructions provided to integrate the kmm-resources plugin including the configuration but when the build runs it only generates the common and iOS pieces not the Android kt file or the xml resource files. Here's a pic of my kmm module structure

![image](https://user-images.githubusercontent.com/30878904/126366943-f94e5f9f-2f5a-47bd-92b6-41bcc69559d1.png)

here's my plugin config:
![image](https://user-images.githubusercontent.com/30878904/126367059-d0f8c986-4c61-4b02-a6d9-1189ea43aa8f.png)

While I have an iOS component I'm primarily interested in the Android piece of this at this point.  I'm running this in Android Studio 4.2.2.

Thanks for any help you can provide.

**Comment by mikelburkhart** [comment]
After reviewing the source for your plugin I noticed that the androidSourceFolder was defaulting to a dir called main whereas in my KMM module it was/is called androidMain. I was able to add this entry to the kmmResourceConfig:

androidSourceFolder.set("androidMain")

and it was able to generate the required Android resources! 

I'm not sure if the KMM android source dir may have changed but it might be good to list that setting in your docs as something that may need to be changed.

**Comment by jcraane** [comment]
Thanks for the info. Dir might have changed indeed (thought it was main a while back). When I create a new KMM project now it defaults to androidMain. I am going to change the plugin to default to androidMain, and document the option more clearly of how/when to change this.

You can expect a new release todat or tomorrow (you can then omit the androidSourceFolder property if you want).

**Comment by jcraane** [comment]
I published a new version: https://plugins.gradle.org/plugin/dev.jamiecraane.plugins.kmmresources which uses androidMain as the default Android source folder now.

**Comment by mikelburkhart** [comment]
I loaded your latest published version and its all working great without the need for the androidSourceFolder property. Thanks for the quick response!
