### ISSUE TITLE
Add default translations to generated methods - enhancement request

### ISSUE THREAD

**Issue by mikelburkhart** [jcraane/kmm-resources#5]
This is a problem we are facing at this point with our common tests. Since the Android side of our kmm project requires an Android Context object, which is not available for our common kotlin tests, this causes our test to be unable to load strings for our translations and our tests to fail. We'd really like to run common tests for our common kotlin classes. If your code generator would insert the default locale string value (defaultLanguage.set("en")) instead of the "" in the generated Android files then when an android context wasn't available they could still return the default string for the locale. I don't know the details for all of the other platforms but am hoping a similar solution could be available for them as well.

For example in the KMMResourcesLocalization.kt file that is generated for Android we have this line

actual fun L.CalendarEvents.chair(): String = localizationContext?.getString(R.string.l_calendarEvents_chair) ?: ""

if your generator could (possibly guarded by a new config property) auto-generate this line instead:

actual fun L.CalendarEvents.chair(): String = localizationContext?.getString(R.string.l_calendarEvents_chair) ?: "Chair"

including the default locale value rather than the empty string, then our common tests would be able to leverage this when running in the default locale to extract the required strings for content validation.

**Comment by jcraane** [comment]
Thanks for the info. This sounds like a nice addition. We already have the default language so this should not be an issue implementing this. I am going to look into this.

**Comment by mikelburkhart** [comment]
Thanks for your consideration, we'll be happy to beta test the changes when you're ready :-)

**Comment by jcraane** [comment]
I have a first implementation ready (not published yet) and want to share some details of how the default translations are generated (all taken from the included sample project, defaultLanguage is NL in this case):

A simple string property is generated as follows
`actual fun L.ExampleContent.Pages.Page1.body(): String = localizationContext?.getString(R.string.l_exampleContent_pages_page1_body) ?: "Body pagina 1"`

Translation with arguments:
`actual fun L.General.withParams(value0: String, value1: String): String = localizationContext?.getString(R.string.l_general_withParams, value0, value1) ?: "Een $value0 tekst met een $value1"`

A basis list:
`
actual fun L.General.basiclist(): List<String> = listOf(
  localizationContext?.getString(R.string.l_general_basiclist0) ?: "optie 1",
  localizationContext?.getString(R.string.l_general_basiclist1) ?: "optie 2"
)
`

List of objects:
`
actual fun L.Listofobjects.Categories.Samplecategory.Content.body(): String {
   val context = localizationContext
   return context?.getString(context.resources.getIdentifier("l.listofobjects.categories.samplecategory.content.$index.body", "string", context.packageName)) ?: "Dit is de body1"
}
actual fun L.Listofobjects.Categories.Samplecategory.Content.title(): String {
   val context = localizationContext
   return context?.getString(context.resources.getIdentifier("l.listofobjects.categories.samplecategory.content.$index.title", "string", context.packageName)) ?: "Dit is de titel1"
}
`

To enable the genration of the default translation the property useDefaultTranslationIfNotInitialized must be set to true in the kmMResourcesConfig section in the Gradle build file. This is to make sure that the context is forgotten
to be initialized and you only see the default translations.

Is this something you can work with?

**Comment by mikelburkhart** [comment]
Yes, this will meet all of our needs at this time.

**Comment by jcraane** [comment]
I have release version 1.0.0-alpha07 with the changes implemented as described above. Could you test it if this works for you? Don't forget to set useDefaultTranslationIfNotInitialized.set(true) in the mkkResourcesConfig (see Readme)

**Comment by mikelburkhart** [comment]
Its working great! Thank you so much.
