### ISSUE TITLE
translation file generation is failing due to translated strings that need to be escaped

### ISSUE THREAD

**Issue by mikelburkhart** [jcraane/kmm-resources#6]
Hello again! We're running into an issue when attempting to integrate our complete list of translations. We have the following simple example data in our strings.yaml file:

general:
  button:
    ok:
      en: "OK"
      ar: "حسنًا"
      ca: "D'acord"
      cs: "OK"
      da: "OK"

When we attempt to build the localizations with this data we get an error from Android Studio about the ca line which contains an apostrophe which from what we understand cannot be escaped in YAML (limitation) but in android strings files it MUST be escaped and if not breaks the build.

It looks like we need your plugin to identify chars that need to be escaped when generating the android strings.xml files and insert the \ in front of the characters as part of the build process. I'm not sure what affect this will have on the iOS side but can assume there may be issues there as well.

Thanks for your assistance.

**Comment by lammertw** [comment]
You should be able to escape the apostrophe in the yaml file:
```
ca: "D\'acord"
```

Currently we're also doing it like this in our project and this should not break anything on iOS.

We'll look more into this to see if we can make it part of the Android generation process.

**Comment by mikelburkhart** [comment]
Thanks for the reply. We did try that but get this when building in Android Studio (4.2.2):

![image](https://user-images.githubusercontent.com/30878904/130962909-822f8226-672f-4a33-8b7c-e2682f0ddb83.png)

**Comment by lammertw** [comment]
That's surprising. @jcraane will look into this more (probably next week)

**Comment by mikelburkhart** [comment]
Thanks for any help ya'll can provide. We have a release early next week where we were hoping to include the functionality reliant on the kmm resources plugin but are blocked at this point.

**Comment by lammertw** [comment]
Can you perhaps attach the yaml file (or at least a part that includes the problem) so I can try running it and see what happens?

**Comment by mikelburkhart** [comment]
Absolutely. The part I pasted above should be able to be used to recreate the issue but here's our complete strings.yaml at this point for reference.
[strings.yaml.zip](https://github.com/jcraane/kmm-resources/files/7060093/strings.yaml.zip)

**Comment by lammertw** [comment]
I think I found the problem.
You can solve this in two ways. When you put double quotes around the text you need to double escape the single quote. When you don't put quotes around the text you can escape it with a single \.
So either:
```ca: "D\\'acord"```
or:
```ca: D\'acord```

**Comment by mikelburkhart** [comment]
Unfortunately neither of those work for us (build still fails), but I did notice that one of my team members submitted a PR that should resolve the issue. Would y'all mind taking a look and considering pulling that in and creating a new release for us?

**Comment by mikelburkhart** [comment]
I stand corrected. I had attempted the changes on one of the 2 strings in the file, but didn't realize that the double quote fix had actually worked for the 1st one. When I applied the fix for both apostraphe's its now building and working. Thanks!

**Comment by mikelburkhart** [comment]
The one side affect that I'm seeing with the `ca: "D\\'acord"` is that the iOS translation file is including an escaping of the apostraphe `"l.general.button.ok" = "D\'acord";` which is not required/used as a pattern in iOS translation files as a standard pattern. I believe that the PR that was created would not end up with this side affect so it may be a better solution than manually updating our translation files to force in \\'s.

**Comment by jcraane** [comment]
I will look at your PR tomorrow and see if I can merge/create a release (just back from vacation).

**Comment by jcraane** [comment]
I published version alpha08 with the PR merged. I did change the replacement to \\ (double backslash) else the \ was not emitted in the output. I added some upgrade docs to upgrade from an loder version to alpha08. You need to change all escaped single quotes \' to just a single ' in the yaml.

Please let me know if it works or not.

**Comment by mikelburkhart** [comment]
Your latest published version is working great. Thanks as usual for the assistance.
